 export const GET_ALL_TOURS_SUCCESS = 'GET_ALL_TOURS_SUCCESS'
 export const GET_ALL_TOURS_FAILED = 'GET_ALL_TOURS_FAILED'

 export const CREATE_TOUR_SUCCESS = 'CREATE_TOUR_SUCCESS';
 export const CREATE_TOUR_FAIL = 'CREATE_TOUR_FAIL';